### ISSUE TITLE
Clarify the results of evaluating `templatel-render-file` in the documentation

### ISSUE THREAD

**Issue by mihaiolteanu** [clarete/templatel#19]
- In https://clarete.li/templatel/api.html, you have the following explanation:

===
Given the HTML template file.html:
```
Hi {{ name }}
```

And the following Lisp code:
```
(templatel-render-file "file.html" ’(("name" . "test")))
```
===
and then you say nothing about the result of evaluating `templatel-render-file`.
That would be my expectation, at least, to see what the library actually does.

- In https://github.com/clarete/templatel#how-does-it-look-like, you also have the template and the `templatel-render-file` call without printing the result of the evaluation.

For people familiar with Python's Jinja or with Common Lisp's html-template, this code might be a no-brainer, but for the others it might not be so evident what `templatel` actually does.

**Comment by clarete** [comment]
hi hi @mihaiolteanu, thanks for taking the time to report the issue! I took a stab at a fix.
Please let me know if you spot anything else 🙇🏾
