### ISSUE TITLE
Can't check if a variable is defined inside template

### ISSUE THREAD

**Issue by markokocic** [clarete/templatel#8]
I want to check inside a template if a variable is defined, something like:

```jinja2
    {% if post %}
      <render post .... /?
    {% endif %}
```

However, I get the following error `Template Error: home.html: Variable `post' not declared`

Is there a way to check if the variable is defined inside a template without triggering the error?

**Comment by clarete** [comment]
Hi @markokocic 👋🏾 

This is a pretty good one, we've been talking about supporting Undefined Variables in templatel at https://github.com/clarete/templatel/issues/7 and I guess you inaugurated the ticket that will track that feature 🎈 🥳 

/cc @semente I know you were interested in this feature too!

Jinja has these things called [Tests](https://jinja2docs.readthedocs.io/en/stable/templates.html#tests) that allow using the `is` expression and they provide a built-in test [defined](https://jinja2docs.readthedocs.io/en/stable/templates.html#defined).  The outcome is something like this:

```jinja2
{% if variable is defined %}
    value of variable: {{ variable }}
{% else %}
    variable is not defined
{% endif %}
```

That takes a few steps to be done:
 1. add a new table for keeping test functions & provide public APIs for managing this table `templatel-env-{add,remove}-test`
 2. add a new binary operator `is` to syntax
 3. compile nodes with new operator `is` into a function call that uses the left operand as a the parameter and the right operand as the name of the filter function that will be retrieved from the table mentioned in the first step
 4. with that, we can write the `defined` test function leveraging the existing variable lookup tooling

This sounds like a fun task to me! 😄

**Comment by markokocic** [comment]
Hi @clarete , what you propose here will work for variables, but what about the properties. For example if I want to display from nested property?

Should it be:
``` jinja
{% if post is defined %}
  {% if post.description is defined %}
{{ post.description }}
  {% endif %}
{% endif %}
```

Or:
``` jinja
{% if post is defined %}
  {% if post.description %}
{{ post.description }}
  {% endif %}
{% endif %}
```

For nested properties / variable IMHO the cleanest, or better say the lispiest way would be to have where the condition would evaluate to nil as soon as one of the properties in the chain is undefined or evaluates to nil.

``` jinja
{% if post.description %}
{{ post.descrpition }}
{% endif %}
```

**Comment by clarete** [comment]
Hi @markokocic thanks for taking the time to give more details into how this would be used.

as to doing both operations in a single operation, I think it'd prevent template authors to differentiate undefined variables from defined variables that contain nil.   That being said, I think we could still achieve that flexibility within a single `if` statement.  This is what I had in mind:

```jinja2
{% if post is defined and post.description %}
  {{ post.description }}
{% endif %}
```

On the behavior of the attribute operator (`.`), it currently does return `nil` even when the key doesn't exist, and that's why one if there would do.  I think this is good but I might introduce a mechanism for asking in a variable contains a key.


What do you think!

**Comment by markokocic** [comment]
Hi @clarete, I would personally optimize for the most common case, as described in my last comment. 

``` jinja
{% if bar.prop1.prop2.prop3 %}
```
This should evaluate to false / nil as soon as `bar` or one of the properties is `nil` or `undefined`. If one need to check if variable or property is defined, that could still be done explicitly using `is defined` as you suggest. Rules for that could be similar.

**Comment by clarete** [comment]
I see, so if you really wanted to check if it's define, we'd still provide you with the `v is defined` test, but by default you wouldn't bother. hmm, I think that make it more consistent with the behavior of `.`.  Then I think maybe we can leave a note here mentioning that it'd be cool if `defined` could also be used with attributes on top of being used for variables.

Thanks for the input here.  This solution sounds more practical too

**Comment by clarete** [comment]
It's out there! implemented in change https://github.com/clarete/templatel/commit/b1e52137ffa86c900b819e8c3c1a0eeae699d654

I'm going to close this ticket but please re-open it if something doesn't work or feel free to open a new one 😄 🙇🏾 

Thank you!
